dependencies:
  - name: nfs-server-provisioner
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 0.3.1
    alias: nfs
  - name: galaxy-cvmfs-csi
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master
    version: 1.3.2
    alias: cvmfs
  - name: galaxy
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master
    version: 3.3.0

