nameOverride: ""
fullnameOverride: ""

configs: {}
  # env-key: env-value

secrets: {}
  # db-password: changeme

nfs:
  persistence:
    enabled: true
    storageClass: "standard"
    size: "500Gi"
  storageClass:
    create: true
    defaultClass: true
    allowVolumeExpansion: true
    reclaimPolicy: "Delete"

cvmfs:
  cache:
    alienCache:
      enabled: true
      storageClass: "nfs"
    localCache:
      enabled: false

galaxy:
  persistence:
    accessMode: "ReadWriteMany"
    storageClass: "nfs"
    size: "300Gi"
  ingress:
    enabled: false
  postgresql:
    persistence:
      storageClass: "standard"
  influxdb:
    enabled: false
