nameOverride: ""
fullnameOverride: ""

configs: {}
  # env-key: env-value

secrets: {}
  # db-password: changeme

persistence:
  nfs:
    name: "nfs-disk"
    # size: 500Gi
    storageClass: "manual"
    accessMode: ReadWriteOnce
    persistentVolume:
      extraSpec:
        gcePersistentDisk:
          # pdName: leo-created-pd
          fsType: ext4
  postgres:
    name: "postgres-disk"
    # size: 500Gi
    storageClass: "manual"
    accessMode: ReadWriteOnce
    persistentVolume:
      extraSpec:
        gcePersistentDisk:
          # pdName: leo-created-pd
          fsType: ext4

nfs:
  persistence:
    enabled: true
    storageClass: "standard"
    size: "500Gi"
  storageClass:
    create: true
    defaultClass: true
    allowVolumeExpansion: true
    reclaimPolicy: "Delete"
    mountOptions:
      - vers=4.2
      - noatime
cvmfs:
  cache:
    alienCache:
      enabled: true
      storageClass: "nfs"
    localCache:
      enabled: false

galaxy:
  image:
    repository: galaxy/galaxy-anvil
    tag: 20.09.5
  persistence:
    accessMode: "ReadWriteMany"
    storageClass: "nfs"
    size: "300Gi"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
      nginx.ingress.kubernetes.io/auth-tls-secret: "{{.Release.Namespace}}/ca-secret"
      nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
      nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      - secretName: "tls-secret"
  postgresql:
    persistence:
      storageClass: "standard"
  influxdb:
    enabled: false
  extraEnv: []
  # - name: WORKSPACE_NAME
  #   valueFrom:
  #     configMapKeyRef:
  #       name: "{{.Release.Name}}-[galaxykubeman|leo]-configs"
  #       key: WORKSPACE_NAME

  # terra:
  #   launch:
  #     workspace: launchWorkspace
  #     namespace: launchProject
  configs:
    file_sources_conf.yml:
      - doc: {{ .Values.terra.launch.workspace }}
        id: {{ .Values.terra.launch.workspace }}
        workspace: {{ .Values.terra.launch.workspace }}
        namespace: {{ .Values.terra.launch.namespace }}
        type: anvil
        on_anvil: True
        # api_url: https://firecloud-orchestration.dsde-dev.broadinstitute.org/api/
        # drs_url: https://us-central1-broad-dsde-dev.cloudfunctions.net/martha_v3
  resources:
    requests:
      cpu: 1
      memory: 6G
      ephemeral-storage: 5Gi
    limits:
      cpu: 4
      memory: 20G
      ephemeral-storage: 20Gi

rbac:
  enabled: true
  serviceAccount: default
