nfs:
  persistence:
    enabled: true
    storageClass: "standard"
    size: "100Gi"
  storageClass:
    create: true
    defaultClass: true
    allowVolumeExpansion: true
    reclaimPolicy: "Delete"

cvmfs:
  cache:
    alienCache:
      enabled: true
      storageClass: "nfs"
    localCache:
      enabled: false

galaxy:
  persistence:
    accessMode: "ReadWriteMany"
    storageClass: "nfs"
  ingress:
    enabled: false
  postgresql:
    persistence:
      storageClass: "standard"
  influxdb:
    enabled: false
