dependencies:
  - name: nfs-server-provisioner
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/anvil/
    version: 1.1.2
    alias: nfs
  - name: rstudio
    repository: https://raw.githubusercontent.com/cloudve/helm-charts/master/
    version: 0.4.0
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 14.8.11
